### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ameygat** [mushorg/glutton#45]
I ran glutton and tried to connect from localhost telnet it crashed showing following error 
My VM is having OS -  Debian GNU/Linux 8

```
root@debian8template:~# go run /opt/go/src/github.com/mushorg/glutton/app/server.go  -log /tmp/glutton.log

  _____ _       _   _
 / ____| |     | | | |
| |  __| |_   _| |_| |_ ___  _ __
| | |_ | | | | | __| __/ _ \| '_ \
| |__| | | |_| | |_| || (_) | | | |
 \_____|_|\__,_|\__|\__\___/|_| |_|

	
INFO[0000] [glutton ] Loading rules from: /etc/glutton/rules.yaml 
INFO[0000] [glutton ] Rules: [Rule: tcp dst port 5001 Rule: tcp dst port 23 or port 2323 or port 23231 Rule: tcp] 
INFO[0000] [freki   ] starting freki on [x.x.x.55]  
INFO[0000] [freki   ] starting proxy.tcp on 6000        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x404c50]

goroutine 27 [running]:
panic(0x753ac0, 0xc4200120b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main.func3.1(0xc4212e4c80, 0xc421305580, 0xc42131ce80, 0xc42133ef40, 0xbb3440, 0xc420024000)
	/opt/go/src/github.com/mushorg/glutton/app/server.go:161 +0x200
created by main.main.func3
	/opt/go/src/github.com/mushorg/glutton/app/server.go:194 +0x14c
exit status 2
```

**Comment by glaslos** [comment]
3936ff3ae3cf6334bc2023f26091f79088d30129 should fix that issue.

**Comment by ameygat** [comment]
Yup that fixed the crash :-)
