### ISSUE TITLE
Glutton will not start when you pass interface perimeter

### ISSUE THREAD

**Issue by dpisano** [mushorg/glutton#93]
When you try and start Glutton right now with a interface perimeter it through's the following error:

```
  _____ _       _   _
 / ____| |     | | | |
| |  __| |_   _| |_| |_ ___  _ __
| | |_ | | | | | __| __/ _ \| '_ \
| |__| | | |_| | |_| || (_) | | | |
 \_____|_|\__,_|\__|\__\___/|_| |_|

	
panic: interface conversion: interface is string, not bool

goroutine 1 [running]:
panic(0x980a40, 0xc42138cc00)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mushorg/glutton.New(0xc421375c20, 0x0, 0x0, 0x0)
	/go/src/github.com/mushorg/glutton/glutton.go:42 +0x2b5
main.main()
	/go/src/github.com/mushorg/glutton/app/server.go:56 +0x19b

```

From what I have been able to tell this might have started in PR #91.

**Comment by nassimabedi** [comment]
I also have this error :slightly_smiling_face:
